import Image from "next/image";
import styles from "./css/techstack.module.css";

export default function TechStack() {
  return (
    <div className={styles.techstack}>
      <div className={styles.layer}>
        <h2>FRAMEWORKS / LIBRARIES / TOOLS</h2>
        <Image
          src={"./icons/spring-boot.svg"}
          height={32}
          width={32}
          alt="icon"
        ></Image>
        <Image
          className={styles.icon}
          src="./icons/hibernate.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/rabbit-mq.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/thymeleaf.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/react-js.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/next-js-blue.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/android-studio.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/git.svg"
          height={32}
          width={32}
          alt="icon"
        />
      </div>

      <div className={styles.layer}>
        <h2>PROGRAMMING LANGUAGES</h2>
        <Image
          className={styles.icon}
          src="./icons/c.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/c++.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/java.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/javascript.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/typescript.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/solidity-purple.svg"
          height={32}
          width={32}
          alt="icon"
        />
      </div>

      <div className={styles.layer}>
        <h2>BLOCKCHAIN</h2>
        <Image
          className={styles.icon}
          src="./icons/ethereum.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/truffle-suite.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/ganache.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/solidity-purple.svg"
          height={32}
          width={32}
          alt="icon"
        />
      </div>

      <div className={styles.layer}>
        <h2>FRONTEND</h2>
        <Image
          className={styles.icon}
          src="./icons/html.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/css.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/sass.svg"
          height={32}
          width={32}
          alt="icon"
        />
      </div>

      <div className={styles.layer}>
        <h2>DATABASE</h2>
        <Image
          className={styles.icon}
          src="./icons/mysql.svg"
          height={32}
          width={32}
          alt="icon"
        />
        <Image
          className={styles.icon}
          src="./icons/mongodb.svg"
          height={32}
          width={32}
          alt="icon"
        />
      </div>
    </div>
  );
}
